---
title: "Pair Wise comparisons"
author: "Taylor A Portman"
date: '2022-06-14'
output: html_document
---
##########SPECIFIC PAIR WISE COMPARISONS#####################

```{r}
library(ggplot2)
library(tidyverse)
library(ggpubr)

compounds_table <- read_csv("~/Google Drive/My Drive/projects/ERLE_fungal_symbionts/IsolatesAlone/RP_Final_rem1177_2_output_tables/compounds_table.csv")

color<- c( "#E64B35B2", "#4DBBD5B2",  "#00A087B2",  '#7E6148B2')

```

1177 Penicillic acid
```{r}
pen.acid<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "Penicillic acid")

pen.plot<- ggplot(pen.acid, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Penicillic acid")+
  xlab("Fungal isolate")+ 
  stat_compare_means(method="anova", label.x=3)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
pen.plot

figure_file <- file.path(figures_dir, 'pairwise_penicillic.acid.png')
ggsave(figure_file, pen.plot, width=15, height=10, unit='cm')

pen.aov<-aov(AUC~Fungi, data=pen.acid)
summary(pen.aov)
 
library(rstatix) 
stat.test <- pen.acid %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```
1154 Caffeic Acid
```{r}
caffeic.acid<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "Caffeic acid")

caffeic.plot<- ggplot(caffeic.acid, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Caffeic acid")+
  xlab("Fungal isolate")+
  stat_compare_means(method="anova", label.x=3)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
caffeic.plot

figure_file <- file.path(figures_dir, 'pairwise_caffeic.acid.png')
ggsave(figure_file, caffeic.plot, width=15, height=10, unit='cm')

caffeic.aov<-aov(AUC~Fungi, data=caffeic.acid)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- caffeic.acid %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```


Adenine
```{r}
adenine<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "Adenine")

adenine.plot<- ggplot(adenine, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Adenine")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova", label.x=1)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
adenine.plot

figure_file <- file.path(figures_dir, 'pairwise_adenine.png')
ggsave(figure_file, adenine.plot, width=15, height=10, unit='cm')

caffeic.aov<-aov(AUC~Fungi, data=adenine)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- adenine %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

Tiglic acid
```{r}
tiglic.acid<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "Tiglic acid")

tiglic.acid.plot<- ggplot(tiglic.acid, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Tiglic acid")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova", label.y=100)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
tiglic.acid.plot

figure_file <- file.path(figures_dir, 'pairwise_tiglic.acid.png')
ggsave(figure_file, tiglic.acid.plot, width=15, height=10, unit='cm')

caffeic.aov<-aov(AUC~Fungi, data=tiglic.acid)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- tiglic.acid %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

Methoxyresorcinol
```{r}
methoxyresorcinol<- compounds_table%>%
  select(Name, name4plot, MW, AUC, Fungi) %>%
  filter( name4plot== "methoxyresorcinol-peak2")

methoxyresorcinol.plot<- ggplot(methoxyresorcinol, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Methoxyresorcinol")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova", label.y=100000000)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
methoxyresorcinol.plot

figure_file <- file.path(figures_dir, 'pairwise_methoxyresorcinol.png')
ggsave(figure_file, methoxyresorcinol.plot, width=15, height=10, unit='cm')

caffeic.aov<-aov(AUC~Fungi, data=methoxyresorcinol)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- methoxyresorcinol %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

Adipic acid

```{r}
adipic.acid<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "Adipic acid")

adipic.acid.plot<- ggplot(adipic.acid, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Adipic acid")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova", label.x=3)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
adipic.acid.plot

figure_file <- file.path(figures_dir, 'pairwise_adipic.acid.png')
ggsave(figure_file, adipic.acid.plot, width=15, height=10, unit='cm')

caffeic.aov<-aov(AUC~Fungi, data=adipic.acid)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- adipic.acid %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

(+)-Piperitol


```{r}
piperitol<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "(+)-Piperitol")

piperitol.plot<- ggplot(piperitol, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "(+) Piperitol")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova")+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
piperitol.plot

figure_file <- file.path(figures_dir, 'pairwise_piperitol.png')
ggsave(figure_file, piperitol.plot, width=15, height=10, unit='cm')

piperitol.aov<-aov(AUC~Fungi, data=piperitol)
summary(piperitol.aov)
 
library(rstatix) 
stat.test <- piperitol %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```
Ferulic acid


```{r}
ferulic.acid<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "NP-019445")

ferulic.acid.plot<- ggplot(ferulic.acid, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Ferulic acid")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova")+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
ferulic.acid.plot

figure_file <- file.path(figures_dir, 'pairwise_ferulic.acid.png')
ggsave(figure_file, ferulic.acid.plot, width=15, height=10, unit='cm')

ferulic.acid.aov<-aov(AUC~Fungi, data=ferulic.acid)
summary(ferulic.acid.aov)
 
library(rstatix) 
stat.test <- ferulic.acid %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

3',4'-Dimethoxyacetophenone


```{r}
dimetho<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "3',4'-Dimethoxyacetophenone")

dimetho.plot<- ggplot(dimetho, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "3',4'-Dimethoxyacetophenone")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova")+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
dimetho.plot

figure_file <- file.path(figures_dir, 'pairwise_dimetho.png')
ggsave(figure_file, dimetho.plot, width=15, height=10, unit='cm')

dimetho.aov<-aov(AUC~Fungi, data=dimetho)
summary(dimetho.aov)
 
library(rstatix) 
stat.test <- dimetho %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```