---
title: "R Notebook"
output: html_notebook
---
---
title: "R Notebook"
output: html_notebook
ABC transporters
```{r}
library(ggplot2)
library(tidyverse)
library(ggpubr)

compounds_table <- read_csv("~/Google Drive/My Drive/projects/ERLE_fungal_symbionts/IsolatesAll_1154/RP_All_1154_output_tables/compounds_table.csv")

color<- c( "#E64B35B2", "#4DBBD5B2",  "#00A087B2",  '#7E6148B2')

figures_dir <- file.path("~/Google Drive/My Drive/projects/ERLE_fungal_symbionts/IsolatesAll_1154/RP_All_1154_output_figures")
tables_dir<- file.path("~/Google Drive/My Drive/projects/ERLE_fungal_symbionts/IsolatesAll_1154/RP_All_1154_output_tables")
```

Phenylpropanoid biosynthesis heat map

Imported revised Table from script below removing repeated peak#s
```{r}
compounds_table$KEGGPathways<- as.factor(compounds_table$"KEGG Pathways")
  
ABC_transporters<- compounds_table%>%
  separate_rows(KEGGPathways, sep= ";")%>%
  filter(KEGGPathways=="ABC transporters")

table_file <- file.path(tables_dir, 'SecondaryPlantMetabolites.csv')
write_csv( ABC_transporters, table_file)
  
```

```{r set_path, message=FALSE, warning=FALSE}
library(dplyr)
compounds_table<-ABC_transporters
  source('functions_cdis_norm_stats.R')
# Create a new tibble with the AUC per each mass from each sample
auc_table_nogap <- compounds_table %>% 
  select(FeatureID, SampleID, AUC)
  
# Transform the dataframe into a matrix-like table
auc_table_nogap <-  spread(auc_table_nogap, SampleID, AUC) %>% 
  column_to_rownames(var = 'FeatureID')
#pivot_longer(auc_table_nogap, names_to = "SampleID", values_to = "AUC")

#auc_table_nogap$FeatureID <- factor(auc_table_nogap$FeatureID, levels=str_sort(auc_table_nogap$FeatureID, numeric = TRUE))

```

```{r}
# Obtaining non-transformed data for differential analysis
norm.matrix <- cycloess.norm(auc_table_nogap)
# Change missing values for zeroes
norm.matrix[is.na(norm.matrix)] <- 0
# Save normalized data, non transformed data for differential analysis
table_file <- file.path(tables_dir, 'normalized_untransformed_auc_table.csv')
write.csv(norm.matrix, table_file, row.names = TRUE)




#norm.matrix <- column_to_rownames(norm.matrix, var = '...1')

# Load compounds table and add a column that has names for identified compounds and FeatureID for the rest (for plotting puRPouses)

#compounds_table <- read_csv(compounds_table)

# Import metadata and fix names
metadata_file <- file.path(tables_dir, 'fixed_metadata.csv')
metadata <- read_csv(metadata_file)

metadata<-metadata%>%
  filter(Fungi== "CTRL"| Fungi=="1154")



```


NOrmalized area under the curve heat map
```{r warning=FALSE}
library(pheatmap)
library(RColorBrewer)
# Initialize graphical device
#dev.off()

# Set sampleID as row.names to annotate heatmap

col_annot <- column_to_rownames(metadata, var = 'SampleID') 
mapcolor <- colorRampPalette(brewer.pal(11, 'RdYlBu'))(100)[100:1]

figure_file <- file.path(figures_dir, 'ABC_transporters_heatmap.pdf')

annot_colors <- list(
  Plant = c(CTRL ='grey', ERLE = 'tomato1', ERIN = 'goldenrod3', BOCU = 'dodgerblue', LEDU= 'seagreen'),
  Fungi = c('CTRL' = 'grey', '1154' = 'plum4'),
  Origin = c(LC_MS2 = '#0086cb', NMR = '#d23936'))

pdf(figure_file)
pheatmap(norm.matrix,
         clustering_distance_rows = 'correlation',
         clustering_distance_cols = 'correlation',
         scale = 'row',
         annotation_col = col_annot,
         annotation_colors = annot_colors,
         color = mapcolor,
         show_rownames = TRUE,
         cutree_cols = 5,
         main = 'All features (scaled AUC)'
)
#dev.off()
```
```{r}
# Extract all features that have names
named_compounds <- compounds_table %>% 
  select(FeatureID, Name, name4plot) %>% 
  filter(!is.na(Name)) %>% 
  distinct()

# Create a matrix of only identified features

named_compounds.matrix <- norm.matrix[rownames(norm.matrix) %in% named_compounds$FeatureID,]
row.names(named_compounds.matrix) <- compounds_table$name4plot[match(row.names(named_compounds.matrix), compounds_table$FeatureID)]

```
```{r}
figure_file <- file.path(figures_dir, 'All_identified_features_heatmap_ABC_transporters_.pdf')

pdf(figure_file, width = 15, height = 10)
pheatmap(named_compounds.matrix,
         clustering_distance_rows = 'correlation',
         #cluster_cols= FALSE,
         clustering_distance_cols = 'correlation',
         scale = 'row',
         annotation_col = col_annot,
         annotation_colors = annot_colors,
         color = mapcolor,
         cutree_cols = 4,
         cutree_rows = 5,
         fontsize_row = 6,
         main = 'Identified features (scaled AUC)'
)
dev.off()
```
