---
title: "Pair Wise comparisons"
author: "Taylor A Portman"
date: '2022-06-14'
output: html_document
---
##########SPECIFIC PAIR WISE COMPARISONS#####################

```{r}
library(ggplot2)
library(tidyverse)
library(ggpubr)

compounds_table <- read_csv("~/Google Drive/My Drive/projects/ERLE_fungal_symbionts/IsolatesAll_1154/RP_All_1154_output_tables/compounds_table_nogap.csv")

color<- c( "#E64B35B2", "#4DBBD5B2",  "#00A087B2",  '#7E6148B2')

figures_dir <- file.path("~/Google Drive/My Drive/projects/ERLE_fungal_symbionts/IsolatesAll_1154/RP_All_1154_output_figures")
tables_dir<- file.path("~/Google Drive/My Drive/projects/ERLE_fungal_symbionts/IsolatesAll_1154/RP_All_1154_output_tables")
```

1177 Penicillic acid
```{r}
pen.acid<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "Penicillic acid")

pen.plot<- ggplot(pen.acid, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  facet_wrap(~Plant)+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Penicillic acid")+
  xlab("Fungal isolate")+ 
  #stat_compare_means(method="anova", label.x=3)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
pen.plot

figure_file <- file.path(figures_dir, 'pairwise_penicillic.acid.png')
ggsave(figure_file, pen.plot, width=15, height=10, unit='cm')

pen.aov<-aov(AUC~Fungi, data=pen.acid)
summary(pen.aov)
 
library(rstatix) 
stat.test <- pen.acid %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```
1154 Caffeic Acid
```{r}
caffeic.acid<- compounds_table%>%
  select(Name, MW, AUC, Fungi,Plant) %>%
  filter( Name== "Caffeic acid")

caffeic.plot<- ggplot(caffeic.acid, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Caffeic acid")+
  xlab("Fungal isolate")
  #stat_compare_means(method="anova", label.x=3)+
  #stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
caffeic.plot

figure_file <- file.path(figures_dir, 'pairwise_caffeic.acid.png')
ggsave(figure_file, caffeic.plot, width=15, height=10, unit='cm')

caffeic.aov<-aov(AUC~Fungi, data=caffeic.acid)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- caffeic.acid %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

caffeic.plot<- ggplot(caffeic.acid, aes(x=Plant, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Caffeic acid")+
  xlab("Plant")+
 # stat_compare_means(method="anova", label.x=3)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
caffeic.plot
figure_file <- file.path(figures_dir, 'pairwise_caffeic.acid.plant.png')
ggsave(figure_file, caffeic.plot, width=15, height=10, unit='cm')
```


Tyrosine
```{r}
tyrosine<- compounds_table%>%
  select(Name, MW, AUC, Fungi, Plant) %>%
  filter( Name== "L-Tyrosine")

tyrosine.plot<- ggplot(tyrosine, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "tyrosine")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova", label.x=1)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
tyrosine.plot

figure_file <- file.path(figures_dir, 'pairwise_tyrosine.png')
ggsave(figure_file, tyrosine.plot, width=15, height=10, unit='cm')

caffeic.aov<-aov(AUC~Fungi, data=tyrosine)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- tyrosine %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

tyrosine.plot<- ggplot(tyrosine, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  facet_wrap(~Plant)+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "tyrosine")+
  xlab("Plant")+
   stat_compare_means(method="anova", label.x=1)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
tyrosine.plot
```

Meconin
```{r}
meconin<- compounds_table%>%
  select(Name, MW, AUC, Fungi, Plant) %>%
  filter( Name== "Meconin")

meconin.plot<- ggplot(meconin, aes(x=Plant, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Ferulic acid")+
  xlab("Fungal isolate")
   #stat_compare_means(method="anova", label.y=100)
  #stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
meconin.plot

figure_file <- file.path(figures_dir, 'pairwise_meconin.png')
ggsave(figure_file, meconin.plot, width=15, height=10, unit='cm')

tiglic.aov<-aov(AUC~Fungi, data=meconin)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- meconin %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

Methoxyresorcinol
```{r}
methoxyresorcinol<- compounds_table%>%
  select(Name, name4plot, MW, AUC, Fungi, Plant) %>%
  filter( Name== "methoxyresorcinol")

methoxyresorcinol.plot<- ggplot(methoxyresorcinol, aes(x=Plant, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Methoxyresorcinol")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova", label.y=100000000)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
methoxyresorcinol.plot

figure_file <- file.path(figures_dir, 'pairwise_methoxyresorcinol.png')
ggsave(figure_file, methoxyresorcinol.plot, width=15, height=10, unit='cm')

 
library(rstatix) 
stat.test <- methoxyresorcinol %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

Adipic acid

```{r}
adipic.acid<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "Adipic acid")

adipic.acid.plot<- ggplot(adipic.acid, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Adipic acid")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova", label.x=3)+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
adipic.acid.plot

figure_file <- file.path(figures_dir, 'pairwise_adipic.acid.png')
ggsave(figure_file, adipic.acid.plot, width=15, height=10, unit='cm')

caffeic.aov<-aov(AUC~Fungi, data=adipic.acid)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- adipic.acid %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

(+)-Piperitol


```{r}
piperitol<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "(+)-Piperitol")

piperitol.plot<- ggplot(piperitol, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "(+) Piperitol")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova")+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
piperitol.plot

figure_file <- file.path(figures_dir, 'pairwise_piperitol.png')
ggsave(figure_file, piperitol.plot, width=15, height=10, unit='cm')

piperitol.aov<-aov(AUC~Fungi, data=piperitol)
summary(piperitol.aov)
 
library(rstatix) 
stat.test <- piperitol %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```
Ferulic acid


```{r}
ferulic.acid<- compounds_table%>%
  select(Name, MW, AUC, Fungi) %>%
  filter( Name== "NP-019445")

ferulic.acid.plot<- ggplot(ferulic.acid, aes(x=Fungi, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "Ferulic acid")+
  xlab("Fungal isolate")+
   stat_compare_means(method="anova")+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
ferulic.acid.plot

figure_file <- file.path(figures_dir, 'pairwise_ferulic.acid.png')
ggsave(figure_file, ferulic.acid.plot, width=15, height=10, unit='cm')

ferulic.acid.aov<-aov(AUC~Fungi, data=ferulic.acid)
summary(ferulic.acid.aov)
 
library(rstatix) 
stat.test <- ferulic.acid %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

3',4'-Dimethoxyacetophenone


```{r}
dimetho<- compounds_table%>%
  select(Name, MW, AUC, Fungi,Plant) %>%
  filter( Name== "3',4'-Dimethoxyacetophenone")

dimetho.plot<- ggplot(dimetho, aes(x=Plant, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "3',4'-Dimethoxyacetophenone")+
  xlab("Plant")+
   stat_compare_means(method="anova")+
  stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
dimetho.plot

figure_file <- file.path(figures_dir, 'pairwise_dimetho.png')
ggsave(figure_file, dimetho.plot, width=15, height=10, unit='cm')

dimetho.aov<-aov(AUC~Fungi, data=dimetho)
summary(dimetho.aov)
 
library(rstatix) 
stat.test <- dimetho %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

NP-019445
```{r}
meconin<- compounds_table%>%
  select(Name, MW, AUC, Fungi, Plant) %>%
  filter( Name== "NP-019445")

meconin.plot<- ggplot(meconin, aes(x=Plant, y=AUC, fill=Fungi, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  theme_classic()+
  scale_color_manual(values=color)+
  scale_fill_manual(values=color)+
  labs(title= "5-Hydroxy-coniferaldehyde")+
  xlab("Fungal isolate")
   #stat_compare_means(method="anova", label.y=100)
  #stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
  
meconin.plot

figure_file <- file.path(figures_dir, 'pairwise_NP-091445.png')
ggsave(figure_file, meconin.plot, width=15, height=10, unit='cm')

tiglic.aov<-aov(AUC~Fungi, data=meconin)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- meconin %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```

Phenylalanine biosynthesis compounds-
L-Tyrosine, Caffeic acid, Meconin, 3'4' dimethoxyacethophenone, NP-019445
```{r}
compounds<- compounds_table%>%
  select(Name, MW, AUC, Fungi, Plant) %>%
  filter( Name== "L-Tyrosine"|Name=="Caffeic acid"| Name=="Meconin"| Name=="3',4'-Dimethoxyacetophenone"| Name=="NP-019445")

compounds$Name <- factor(compounds$Name , levels=c("L-Tyrosine", "Caffeic acid", "Meconin", "3',4'-Dimethoxyacetophenone","NP-019445"))
compounds$Plant<-factor(compounds$Plant, levels=c("CTRL","ERLE", "ERIN", "BOCU", "LEDU"))
compounds.plot<- ggplot(compounds, aes(x=Plant, y=AUC, fill=Name, color=Fungi))+
  geom_boxplot(alpha=0.7)+
  facet_wrap(~Name, scales="free")+
  theme_classic()+
  scale_color_manual(values=c("black","grey"))+
  scale_fill_manual(values=c("red","orange","yellow", "purple", "blue"))+
  labs(title= "Phenylalanine biosynthesis compounds")+
  xlab("Plant")
   #stat_compare_means(method="anova", label.y=100)
  #stat_compare_means(label="p.signif", method="t.test", ref.group="CTRL", hide.ns=TRUE)
compounds.plot

figure_file <- file.path(figures_dir, 'AllPhenylpropanoids1.png')
ggsave(figure_file, compounds.plot, width=10, height=5, unit='in')

tiglic.aov<-aov(AUC~Fungi, data=meconin)
summary(caffeic.aov)
 
library(rstatix) 
stat.test <- meconin %>%
  pairwise_t_test(
    AUC ~ Fungi, paired = FALSE,
    p.adjust.method = "none"
    )
stat.test

```
