---
title: "Class Composition"
author: "Taylor A Portman"
date: "5/23/2022"
output: html_document
---


```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggrepel)
library(ggsci)
library(pheatmap)
library(RColorBrewer)
library(readxl)
library(UpSetR)
source('functions_cdis_diff.R')
```

Change to what data you are using
```{r}
data= 'RP'
```

# 2. Import data


Because differential analysis includes the calculations of means, the data to be used in this section is the normalized untransformed data

```{r set_path, message=FALSE, warning=FALSE}
# set path variables
project_dir <- getwd()
project_name <- 'RP_Final_rem1177_2'
figures_dir <- file.path(project_dir, paste0(project_name, '_output_figures'))
tables_dir <- file.path(project_dir,  paste0(project_name, '_output_tables'))
norm_auc_table_file <- file.path(tables_dir, 'normalized_untransformed_auc_table.csv')

# If the flag was setted before, nothing needs to be changed here, the correct file will be automatically used

  compounds_table_file <- file.path(tables_dir, 'compounds_table.csv')


# Load auc_table

norm.matrix <- read_csv(norm_auc_table_file)
norm.matrix <- column_to_rownames(norm.matrix, var = '...1')

# Load compounds table and add a column that has names for identified compounds and FeatureID for the rest (for plotting puRPouses)

compounds_table <- read_csv(compounds_table_file)

# Import metadata and fix names
metadata_file <- file.path(tables_dir, 'fixed_metadata.csv')
metadata <- read_csv(metadata_file)



```

```{r}
KEGG_file<-file.path("data/KEGG_rank_all_modified.csv")
KEGG<- read_csv(KEGG_file)

KEGG.dat<-KEGG%>%
  filter(!Comment=="Downregulated")
```


```{r}
class.plot<- ggplot(KEGG.dat)+
geom_bar(aes(y=reorder(KEGGPathways, -n), x=n,fill=Comment), stat="identity", alpha=0.7, )+
  facet_wrap(~isolate)+
  scale_fill_manual(values = c("tomato2"))+
  theme_classic()+xlab("Number of Features")+ylab("KEGG Pathways")+
  labs(title="Upregulated KEGG pathways")
class.plot

figure_file <- file.path(figures_dir, 'KEGG_rank_all.modified.png')
ggsave(figure_file, class.plot, width=30, height=10, unit='cm')

```


```{r}
diff.exp<- read.csv("RP_Final_rem1177_2_output_tables/Sig.diff.expressed.allIsolates_L2FC_0.3.csv")


diff.exp$KEGGPathways<-as.factor(diff.exp$"KEGG.Pathways")  
KEGG_all<- diff.exp%>% 
  select(FeatureID, Name, KEGGPathways, Comment, isolate) %>% 
  separate_rows(KEGGPathways, sep = ';')

table_file <- file.path(tables_dir, 'KEGG_all_Isolates.csv')
write_csv( KEGG_all, table_file)


table_file<- file.path( tables_dir,"KEGG_all_Isolates_mod.csv")
KEGG_all_mod<- read.csv(table_file)

KEGG_all_count_mod<- KEGG_all_mod%>% 
  select(FeatureID, KEGGPathways, Comment, isolate) %>% 
  separate_rows(KEGGPathways, sep = ';') %>% 
 filter(Comment == "Upregulated") %>%
  group_by(KEGGPathways, Comment, isolate ) %>% 
  count(KEGGPathways) %>%
   drop_na(KEGGPathways)
```

```{r}
KEGG.plot<- ggplot(KEGG_all_count_mod)+
geom_bar(aes(y=reorder(KEGGPathways, -n), x=n,fill= Comment), stat="identity", alpha=0.7)+
  facet_wrap(~isolate)+
  scale_fill_manual(values = c("grey"))+
  theme_classic()+xlab("Number of Features")+ylab("KEGG Pathways")+
  labs(title="Upregulated KEGG pathways")
KEGG.plot

figure_file <- file.path(figures_dir, 'KEGG_rank_all.modified.png')
ggsave(figure_file, KEGG.plot, width=30, height=10, unit='cm')
```



#################################################################################
```{r}

F1154.sig$Fungi<- '1154'
F1177.sig$Fungi<- '1177'
F1246.sig$Fungi<- '1246'


sig.data.all<- rbind(F1154.sig, F1177.sig, F1246.sig)
#compounds_table$Class <- gsub( "Lignin", "Phenol", compounds_table$Class)
sig.data.all$Class <- gsub("Tannin","Other",  sig.data.all$Class)

sig.data.all<- sig.data.all %>%
  mutate(class = case_when(
    endsWith(Class, "Lignin") ~ "Phenol",
    endsWith(Class, "Tannin") ~ "Highly oxygenated compounds"
  ))%>%
  select(FeatureID, Class, Fungi, Comment)%>%
  count(Class, Fungi, Comment)
  


stack.class<-ggplot(sig.data.all, aes(fill=Class, y=n, x=Fungi)) + 
    facet_wrap(~Comment)+
    geom_bar(position="fill", stat="identity")+
   scale_fill_brewer(palette = 'Set2')+
  theme_classic()+
  ylab('Percent abundance of compounds')+
  xlab('Fungal isolates')+
  labs(title= "Differentially expressed compounds by compound class",
       comment="Differetally expressed compounds pval.adj< 0.05 ")
stack.class
figure_file <- file.path(figures_dir, 'Class.Percent.abund.png')
ggsave(figure_file, stack.class, dpi=400)

stack.class2<-ggplot(sig.data.all, aes(fill=Class, y=n, x=Fungi)) + 
  facet_wrap(~Comment)+
    geom_bar(position="stack", stat="identity")+
  scale_fill_brewer(palette = 'Set2')+
  ylab('Number of compounds')+
  xlab('Fungal isolates')+
  labs(title= "Differentially expressed compounds by compound class",
       caption="Differetally expressed compounds pval< 0.05 ")+
  theme_classic()
stack.class2
figure_file <- file.path(figures_dir, 'Class.Relative.abund.png')
ggsave(figure_file, stack.class2, dpi=400)
```


